// Constants.js
export const GAME_CONSTANTS = {
  NBR_OF_DICES: 5,
  NBR_OF_THROWS: 3,
  MIN_SPOT: 1,
  MAX_SPOT: 6,
  BONUS_THRESHOLD: 63,
  BONUS_POINTS_LIMIT: 63,
  BONUS_POINTS: 50,
  MAX_NBR_OF_SCOREBOARD_ROWS: 7,
  SCOREBOARD_KEY: '@scoreboard',
};
